version: '3'

volumes:
  postgres_data:
      driver: local

services:
  consul:
    image: consul:latest
    command: agent -dev -ui -client=0.0.0.0
    container_name: consul
    restart: 'always'
    ports:
        - 8500:8500
        - 8600:8600
          
  postgres:
      image: postgres      
      volumes:
        - postgres_data:/var/lib/postgresql/data
      restart: 'always'
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
  
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev
    restart: 'always'
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: "5432"
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: password
    ports:
      - 8082:8080
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:management-alpine    
    container_name: 'rabbitmq'
    restart: 'always'
    ports:
        - 5672:5672
        - 8083:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      # HOSTNAME: my-rabbit
    # volumes:
    #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    # networks:
    #     - rabbitmq_go_net

# networks:
#   rabbitmq_go_net:
#     driver: bridge
  # activemq:  
  #   image: vromero/activemq-artemis:alpine-latest
  #   container_name: activemq
  #   restart: 'always'
  #   environment:
  #     ARTEMIS_USERNAME: admin
  #     ARTEMIS_PASSWORD: admin
  #     # AMQ_USER=quarkus -e AMQ_PASSWORD=quarkus 
  #   ports:
  #     - 8161:8161
  #     - 61616:61616
  #     - 5672:5672
        
  # keycloak:
  #     image: bitnami/keycloak:latest
  #     #command: start-dev
  #     environment:
  #       KEYCLOAK_DATABASE_HOST: postgres
  #       KEYCLOAK_DATABASE_PORT: 5432
  #       #DB_ADDR: postgres
  #       KEYCLOAK_DATABASE_NAME: keycloak
  #       KEYCLOAK_DATABASE_USER: keycloak
  #       KEYCLOAK_DATABASE_SCHEMA: public
  #       KEYCLOAK_DATABASE_PASSWORD: password
  #       KEYCLOAK_ADMIN: admin
  #       KEYCLOAK_ADMIN_PASSWORD: admin                
  #       KEYCLOAK_LOGLEVEL: DEBUG
  #       ROOT_LOGLEVEL: DEBUG

  #       DB_VENDOR: postgres
  #       DB_ADDR: localhost
  #       DB_DATABASE: keycloak
  #       DB_USER: keycloak
  #       DB_SCHEMA: public
  #       DB_PASSWORD: password
  #       KEYCLOAK_USER: admin
  #       KEYCLOAK_PASSWORD: password
  #       #KEYCLOAK_HTTP_PORT: 8080
  #       #KEYCLOAK_HTTPS_PORT: 8443
  #       #KEYCLOAK_HOSTNAME: keycloak.localhost
  #       # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
  #       #KEYCLOAK_JDBC_PARAMS:  "ssl=true"
  #     ports:
  #       - 8080:8080
  #       - 8443:8443
  #     depends_on:
  #       - postgres